# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: beta-xcode6.3
script:
  - xctool -project BINList.xcodeproj -scheme BINList -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
