# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: beta-xcode6.3
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xctool -project BINList.xcodeproj -scheme BINList -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
